school_management_system/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('home/',home,name='home'),
    path('',login_view,name='login'),
    path('logout/', logout_view, name='logout'),
    path('staff/',staff_list,name='staff'),
    path('addStaff/', add_staff, name='add_staff'),
    path('delete_staff/<int:staff_id>/', delete_staff, name='delete_staff'),
    path('edit_staff/<int:staff_id>/',edit_staff,name='edit_staff'),
    path('students/', student_list, name='student_list'),
    path('students/add/', add_student, name='add_student'),
    path('delete_student/<int:student_id>/', delete_student, name='delete_student'),
    path('edit_student/<int:student_id>/', edit_student, name='edit_student'),
    path('subject/', subject_list, name='subject_list'),
    path('subject/add/', add_subject, name='add_subject'),
    path('delete_subject/<int:subject_id>/', delete_subject, name='delete_subject'),
    path('classes/', classes_list, name='classes_list'),
    path('classes/add/', add_class, name='add_class'),
    path('delete_class/<int:class_id>/', delete_class, name='delete_class'),
    path('payments/', payment_list, name='payment_list'),
    path('payments/add/', add_payment, name='add_payment'),
    path('edit_payment/<int:payment_id>/', edit_payment, name='edit_payment'),
    path('delete_payment/<int:payment_id>/', delete_payment, name='delete_payment'),
    path('class_register/', class_register_list, name='class_register_list'),
    path('class_register/add/', add_class_register, name='add_class_register'),
    path('delete_class_register/<int:class_register_id>/', delete_class_register, name='delete_class_register'),
    path('staff_classes/<int:staff_id>/', staff_classes, name='staff_classes'),
    path('view_student/<int:student_id>/', view_student_details, name='view_student_details'),
    path('update_marks/<int:class_register_id>/', update_marks, name='update_marks'),
]

term_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('school_management_system.urls')),
]

school_management_system/models.py
from typing import Any
from django.db import models


class Staff(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.BigIntegerField()
    join_date = models.DateField()
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.BigIntegerField()
    phone = models.BigIntegerField()

    def __str__(self):
        return self.name

class Payment(models.Model):
    total_amount = models.IntegerField()
    due_amount = models.IntegerField()
    paid_amount = models.IntegerField()
    payment_date = models.DateField()
    due_date = models.DateField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='payments')

class Subject(models.Model):
    subject_name = models.CharField(max_length=100)

    def __str__(self):
        return self.subject_name



class Class(models.Model):
    class_time = models.TimeField(null=True)
    class_count = models.IntegerField()
    teacher = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='classes')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='classes')

    def __str__(self):
        return f'{self.subject} at {self.class_time} by {self.teacher}'


class ClassRegister(models.Model):
    classes = models.ForeignKey(Class,on_delete=models.CASCADE,related_name='registration')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='registration')
    marks = models.IntegerField(default=0)

class SuperKey(models.Model):
    payment_id = models.ForeignKey(Payment,on_delete=models.CASCADE, default=1)
    class_reg_id = models.ForeignKey(ClassRegister,on_delete=models.CASCADE, default = 1)

school_management_system/forms.py
from django import forms
from .models import *

class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = '__all__' 
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'join_date': forms.DateInput(attrs={'class': 'form-control','type':'date'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        } 

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'dob', 'age', 'phone']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'dob': forms.DateInput(attrs={'class': 'form-control', 'type':'date'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'
        widgets = {
            'subject_name':forms.TextInput(attrs={'class':'form-control'}),
        }

class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['class_count','class_time', 'teacher', 'subject']
        widgets = {
            'class_count': forms.TextInput(attrs={'class': 'form-control'}),
            'class_time':forms.TimeInput(attrs={'class': 'form-control', 'type':'time'}),
            'teacher': forms.Select(attrs={'class': 'form-control'}),
            'subject': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['teacher'].queryset = Staff.objects.all()
        self.fields['subject'].queryset = Subject.objects.all()

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['student','total_amount', 'due_amount', 'paid_amount', 'payment_date', 'due_date']
        widgets = {
            'total_amount':forms.TextInput(attrs={'class': 'form-control'}),
            'due_amount':forms.TextInput(attrs={'class': 'form-control'}),
            'paid_amount':forms.TextInput(attrs={'class': 'form-control'}),
            'payment_date':forms.DateInput(attrs={'class': 'form-control','type':'date'}),
            'due_date':forms.TextInput(attrs={'class': 'form-control','type':'date'}),
            'student':forms.Select(attrs={'class':'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['student'].queryset = Student.objects.all()

class ClassRegisterForm(forms.ModelForm):
    class Meta:
        model = ClassRegister
        fields = ['student','classes']
        widgets = {
            'student':forms.Select(attrs={'class':'form-control'}),
            'classes':forms.Select(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add queryset for dropdowns
        self.fields['classes'].queryset = Class.objects.all()
        self.fields['student'].queryset = Student.objects.all()

class UpdateMarkForm(forms.ModelForm):
    class Meta:
        model = ClassRegister
        fields = ['marks']
        widgets = {
            'marks': forms.TextInput(attrs={'class':'form-control'}),
        }

school_management_system/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login,logout
from .models import *
from .forms import *
from django.http import JsonResponse

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_superuser:
            login(request, user)
            # Redirect to a success page.
            return redirect('home')
        else:
            # Return an 'invalid login' error message.
            return render(request, 'html/login.html', {'error_message': 'Invalid login'})
    else:
        return render(request, 'html/login.html')
def logout_view(request):
    logout(request)
    return redirect('login') 
# Create your views here.
def home(request):
    # Count the number of items in each database table
    staff_count = Staff.objects.count()
    student_count = Student.objects.count()
    subject_count = Subject.objects.count()
    class_count = Class.objects.count()

    context = {
        'staff_count': staff_count,
        'student_count': student_count,
        'subject_count': subject_count,
        'class_count': class_count,
    }
    return render(request, 'html/home.html', context)

def staff_list(request):
    records = Staff.objects.all()
    return render(request, 'html/staff.html', {'records': records})

def add_staff(request):
    if request.method == 'POST':
        form = StaffForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            return redirect('staff')  # Redirect to the staff list page after successfully adding staff
    else:
        form = StaffForm()
    return render(request, 'html/add_staff.html', {'form': form})

def edit_staff(request,staff_id):
    staff = get_object_or_404(Staff, id=staff_id)
    if request.method == 'POST':
        form = StaffForm(request.POST, instance=staff)
        if form.is_valid():
            form.save()
            return redirect('staff')  # Redirect to the staff list page after successfully editing staff
    else:
        form = StaffForm(instance=staff)
    return render(request, 'html/edit_staff.html', {'form': form, 'staff': staff})

def delete_staff(request, staff_id):
    staff = get_object_or_404(Staff, id=staff_id)
    
    if request.method == 'POST':
        staff.delete()
        return JsonResponse({'message': 'Staff member deleted successfully'}, status=200)

    return JsonResponse({'message': 'Invalid request'}, status=400)

def student_list(request):
    students = Student.objects.all()
    return render(request, 'html/students.html', {'students': students})

def add_student(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('student_list')
    else:
        form = StudentForm()
    return render(request, 'html/add_student.html', {'form': form})

def edit_student(request, student_id):
    # Fetch the student object from the database
    student = get_object_or_404(Student, id=student_id)

    if request.method == 'POST':
        # Populate the form with the POST data and instance of the student
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student_list')
    else:
        # Populate the form with the instance of the student
        form = StudentForm(instance=student)

    return render(request, 'html/edit_student.html', {'form': form})

def delete_student(request, student_id):
    staff = get_object_or_404(Student, id=student_id)
    
    if request.method == 'POST':
        staff.delete()
        return JsonResponse({'message': 'Student member deleted successfully'}, status=200)

    return JsonResponse({'message': 'Invalid request'}, status=400)

def subject_list(request):
    subjects = Subject.objects.all()
    return render(request, 'html/subjects.html', {'subjects': subjects})

def add_subject(request):
    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('subject_list')
    else:
        form = SubjectForm()
    return render(request, 'html/add_subject.html', {'form': form})

def delete_subject(request, subject_id):
    staff = get_object_or_404(Subject, id=subject_id)
    
    if request.method == 'POST':
        staff.delete()
        return JsonResponse({'message': 'Subject deleted successfully'}, status=200)

    return JsonResponse({'message': 'Invalid request'}, status=400)

def classes_list(request):
    classes = Class.objects.all()
    return render(request, 'html/classes.html', {'classes': classes})

def add_class(request):
    if request.method == 'POST':
        form = ClassForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('classes_list')
    else:
        form = ClassForm()
    return render(request, 'html/add_class.html', {'form': form})

def delete_class(request, class_id):
    staff = get_object_or_404(Class, id=class_id)
    
    if request.method == 'POST':
        staff.delete()
        return JsonResponse({'message': 'Class deleted successfully'}, status=200)

    return JsonResponse({'message': 'Invalid request'}, status=400)

def payment_list(request):
    payments = Payment.objects.all()
    return render(request, 'html/payments.html', {'payments': payments})

def add_payment(request):
    if request.method == 'POST':
        form = PaymentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('payment_list')
    else:
        form = PaymentForm()
    return render(request, 'html/add_payment.html', {'form': form})

def edit_payment(request, payment_id):
    # Fetch the payment object from the database
    payment = get_object_or_404(Payment, id=payment_id)

    if request.method == 'POST':
        # Populate the form with the POST data and instance of the payment
        form = PaymentForm(request.POST, instance=payment)
        if form.is_valid():
            form.save()
            return redirect('payment_list')
    else:
        # Populate the form with the instance of the payment
        form = PaymentForm(instance=payment)

    return render(request, 'html/edit_payment.html', {'form': form})

def delete_payment(request, payment_id):
    staff = get_object_or_404(Payment, id=payment_id)
    
    if request.method == 'POST':
        staff.delete()
        return JsonResponse({'message': 'Payment deleted successfully'}, status=200)

    return JsonResponse({'message': 'Invalid request'}, status=400)

def class_register_list(request):
    registrations = ClassRegister.objects.all()
    return render(request, 'html/class_register_list.html', {'registrations': registrations})

def add_class_register(request):
    if request.method == 'POST':
        form = ClassRegisterForm(request.POST)
        if form.is_valid():
            # Check if the class has already been registered x times
            class_obj = form.cleaned_data['classes']
            if class_obj.registration.count() >= class_obj.class_count:
                # Return error message or handle accordingly
                pass
            else:
                form.save()
                return redirect('class_register_list')
    else:
        form = ClassRegisterForm()
    return render(request, 'html/add_class_register.html', {'form': form})

def delete_class_register(request, class_register_id):
    staff = get_object_or_404(Payment, id=class_register_id)
    
    if request.method == 'POST':
        staff.delete()
        return JsonResponse({'message': 'Registration deleted successfully'}, status=200)

    return JsonResponse({'message': 'Invalid request'}, status=400)


def staff_classes(request, staff_id):
    staff = Staff.objects.get(pk=staff_id)
    classes_teaching = Class.objects.filter(teacher=staff).values_list('subject', flat=True)
    return JsonResponse(list(classes_teaching), safe=False)


def view_student_details(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    
    # Retrieve payments and classes registered for the student
    payments = Payment.objects.filter(student=student)
    class_registers = ClassRegister.objects.filter(student=student)
    
    context = {
        'student': student,
        'payments': payments,
        'class_registers': class_registers,
    }
    return render(request, 'html/student_detail.html', context)

def update_marks(request, class_register_id):
    class_register = ClassRegister.objects.get(pk=class_register_id)
    
    if request.method == 'POST':
        form = UpdateMarkForm(request.POST, instance=class_register)
        if form.is_valid():
            form.save()
            return redirect('view_student_details', student_id=class_register.student.id) # Redirect to the student details page after saving
    else:
        form = UpdateMarkForm(instance=class_register)
    
    return render(request, 'html/update_marks.html', {'form': form})

school_management_system/templates/html/add_class.html
{% extends "html/base.html" %}
{% block title %}Add Class{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Class</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add Class</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

school_management_system/templates/html/add_class_register.html
{% extends "html/base.html" %}
{% block title %}Registration{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Registration</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

school_management_system/templates/html/add_payment.html
{% extends "html/base.html" %}
{% block title %}Add Payment{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Payment</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add Payment</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

school_management_system/templates/html/add_staff.html
{% extends "html/base.html" %}
{% block title %}Add Staff{% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        {% comment %} <div class="col-md-3">
            {% include 'html/sidebar.html' %}
        </div> {% endcomment %}
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Staff</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_name">Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email:</label>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            <label for="id_phone">Phone:</label>
                            {{ form.phone }}
                        </div>
                        <div class="form-group">
                            <label for="id_join_date">Join Date:</label>
                            {{ form.join_date }}
                        </div>
                        <div class="form-group">
                            <label for="id_address">Address:</label>
                            {{ form.address }}
                        </div>
                        <button type="submit" class="btn btn-success btn-block mt-2">Add Staff</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

school_management_system/templates/html/add_student.html
{% extends "html/base.html" %}
{% block title %}Add Student{% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        {% comment %} <div class="col-md-3">
            {% include 'html/sidebar.html' %}
        </div> {% endcomment %}
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Staff</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add Student</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

school_management_system/templates/html/add_subject.html
{% extends "html/base.html" %}
{% block title %}Add Student{% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        {% comment %} <div class="col-md-3">
            {% include 'html/sidebar.html' %}
        </div> {% endcomment %}
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Staff</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add Subject</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

school_management_system/templates/html/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <style>
        body {
            {% comment %} background-image: url("{% static 'img/images.jpeg' %}"); {% endcomment %}
            background-repeat: no-repeat;
            background-size: cover;
            height: 100vh;
            margin: 0;
            overflow: hidden;
            
        }
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f4f4f4;
            color: #333333;
        }
    
        .card {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    
        .card-header {
            background-color: #007bff;
            color: #ffffff;
            border-radius: 10px 10px 0 0;
        }
    
        .list-group-item {
            background-color: #ffffff;
            border-bottom: 1px solid #e0e0e0;
        }
    
        .list-group-item:last-child {
            border-bottom: none;
        }
    
        .list-group-item strong {
            color: #007bff;
        }
    </style>
    </head>
    <body>
        {% include 'html/navbar.html' %}
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        
        {% block content %}
        {% endblock %}
        <script src="" async defer></script>
    </body>
</html>

school_management_system/templates/html/classes.html
{% extends "html/base.html" %}
{% block title %}Staff{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% include 'html/sidebar.html' %}
        <div class="col">
            <div class="row mb-3">
                <div class="col-md-auto mt-5">
                    <a href="{% url 'add_class' %}" class="btn btn-primary">Add Class</a>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <table class="table" id="staff-table">
                        <thead>
                            <tr>
                                <th>Class Count</th>
                                <th>Class Time</th>
                                <th>Teacher</th>
                                <th>Subject</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for class_obj in classes %}
                                <tr data-class-id="{{ class_obj.id }}">
                                    <td>{{ class_obj.class_count }}</td>
                                    <td>{{ class_obj.class_time }}</td>
                                    <td>{{ class_obj.teacher }}</td>
                                    <td>{{ class_obj.subject }}</td>
                                    <td>
                                        <button class='btn btn-danger btn-delete'>Delete</button>
                                    </td>
                                </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.btn-delete').forEach(button => {
        button.addEventListener('click', function() {
            const tr = this.closest('tr');
            const studentId = tr.getAttribute('data-class-id');
            
            fetch(`/delete_class/${studentId}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json'
                }
            })
            .then(response => {
                if (response.ok) {
                    // If deletion is successful, remove the row from the table
                    tr.remove();
                } else {
                    console.error('Error deleting staff member');
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
        });
    });
});
</script>
{% endblock content %}

school_management_system/templates/html/edit_payment.html
{% extends "html/base.html" %}
{% block title %}Edit Payment{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Payment</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

school_management_system/templates/html/edit_staff.html
{% extends "html/base.html" %}
{% block title %}Add Staff{% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        {% comment %} <div class="col-md-3">
            {% include 'html/sidebar.html' %}
        </div> {% endcomment %}
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center">Add Staff</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_name">Name:</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email:</label>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            <label for="id_phone">Phone:</label>
                            {{ form.phone }}
                        </div>
                        <div class="form-group">
                            <label for="id_join_date">Join Date:</label>
                            {{ form.join_date }}
                        </div>
                        <div class="form-group">
                            <label for="id_address">Address:</label>
                            {{ form.address }}
                        </div>
                        <button type="submit" class="btn btn-success btn-block mt-2">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}